### ISSUE TITLE
Use upstream go-etcd

### ISSUE THREAD

**Issue by benmccann** [flynn-archive/flynn-host#14]
I've been trying to get the changes to the dockerclient merged back upstream and could try helping here as well. It looks like there's only one commit different between the two (https://github.com/flynn/go-etcd/commit/bb6bca27bd279991ba3842c25f25e3316883ce6a). @titanous is there anything I should tell them as per the reason for the change?

**Comment by titanous** [comment]
Yep, I needed `Nodes` to be a slice of pointers so that I could implement a fake version of etcd for tests that used `Node` internally as the type for the tree of data stored. Also, we were constantly getting the address of nodes in the `Nodes` slice, so it simplified things.

https://github.com/flynn/strowger/blob/a59db1f76f71a7439f71ae3aec552888f074e34f/setup_test.go#L31

**Comment by benmccann** [comment]
I got the change merged upstream. Would love to see Strowger switched to use the upstream go-etcd now

**Comment by titanous** [comment]
Done, thanks!

**Comment by benmccann** [comment]
cool! i submitted the most recent change to go-dockerclient upstream yesterday as well

**Comment by benmccann** [comment]
Hmm, actually it looks like that change doesn't merge cleanly to go-docker client because Flynn's version doesn't have https://github.com/fsouza/go-dockerclient/commit/d5d5bde377bce075d7d54ed8d521e34ea2d9d0af  Maybe you could merge that change into Flynn's fork so that I can see how the two changes work together?

**Comment by titanous** [comment]
@benmccann We actually do the demultiplexing of the stream at the edge since the attach output from go-dockerclient is typically put right back into a TCP stream.
